# frozen_string_literal: true

#source "https://rubygems.org"
source "http://mirror.ops.rhcloud.com/mirror/ruby/"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "ffi", "~> 1.12.1"
gem "cucumber", "~> 3.1.2"
gem "selenium-webdriver", "~> 3.142.7"
gem "gmail", "~> 0.7.1"
