# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "ffi", "~> 1.9.25"
gem "cucumber-expressions", "~> 6.0.1"
gem "cucumber", "~> 3.1.1"
gem "selenium-webdriver", "~> 3.13.0"
gem "gmail"
gem "rubyzip", "~> 1.2.2"
