# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem "ffi", "1.9.25"
gem "cucumber-expressions", "6.0.0"
gem "cucumber", "3.1.1"
gem "selenium-webdriver", "3.12.0"
gem "gmail", "0.6.0"
gem "htmlentities", "4.3.4"
